/**
 * POST /api/admin/remotion/render-reel
 *
 * Renders the Junction 2 Bridge photo reel as an h264 MP4.
 * Reads composition config from scratch/j2-bridge-render-input.json
 * (generated by scripts/upload-reel-photos.ts).
 *
 * Auth: cookie-bound Supabase session (same gate as /api/admin/remotion/render).
 * Flag: FEATURE_REMOTION=1 required.
 * Memory: 3 GB (Vercel Pro) — renderMedia for 64 photos @ 1080×1920 is CPU+RAM intensive.
 */

import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { randomUUID } from "node:crypto";

import { NextResponse } from "next/server";
import chromium from "@sparticuz/chromium";
import { renderMedia, selectComposition } from "@remotion/renderer";
import { createClient as createSupabaseClient } from "@supabase/supabase-js";

import { isRemotionEnabled } from "@/lib/creatives/types";
import { createClient } from "@/lib/supabase/server";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const maxDuration = 600;
export const config = { memory: 3008 };

const BUCKET = "campaign-assets";
const COMPOSITION_ID = "PhotoReelStatic";
const SIGNED_URL_TTL_SEC = 60 * 60 * 24 * 7;

interface RenderInput {
  compositionId: string;
  inputProps: {
    photos: string[];
    framesPerPhoto: number;
  };
}

function getBundlePath(): string {
  return path.join(process.cwd(), ".remotion/bundle");
}

function createStorageAdminClient() {
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!supabaseUrl || !serviceRoleKey) {
    throw new Error(
      "Supabase storage admin requires NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY.",
    );
  }

  return createSupabaseClient(supabaseUrl, serviceRoleKey, {
    auth: { persistSession: false },
  });
}

async function readRenderInput(): Promise<RenderInput> {
  const filePath = path.join(process.cwd(), "scratch/j2-bridge-render-input.json");
  try {
    const raw = await fs.readFile(filePath, "utf-8");
    return JSON.parse(raw) as RenderInput;
  } catch {
    throw new Error(
      "scratch/j2-bridge-render-input.json not found. " +
        "Run `npx tsx scripts/upload-reel-photos.ts` locally first and commit the output.",
    );
  }
}

export async function POST(): Promise<NextResponse> {
  if (!isRemotionEnabled()) {
    return NextResponse.json(
      {
        error:
          "FEATURE_REMOTION is off — enable it in environment variables to run renders.",
      },
      { status: 503 },
    );
  }

  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: "Unauthorised" }, { status: 401 });
  }

  const bundlePath = getBundlePath();
  try {
    await fs.access(bundlePath);
  } catch {
    return NextResponse.json(
      {
        error:
          "Remotion bundle not found. Run `npm run bundle-remotion` before deploying.",
      },
      { status: 500 },
    );
  }

  let renderInput: RenderInput;
  try {
    renderInput = await readRenderInput();
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return NextResponse.json({ error: message }, { status: 500 });
  }

  if (!Array.isArray(renderInput.inputProps?.photos) || renderInput.inputProps.photos.length === 0) {
    return NextResponse.json(
      { error: "Render input has no photos. Re-run the upload script." },
      { status: 500 },
    );
  }

  const renderId = randomUUID();
  const storagePath = `remotion-renders/${user.id}/${renderId}.mp4`;
  const tempFile = path.join(os.tmpdir(), `remotion-reel-${renderId}.mp4`);

  // === Vercel Lambda writable-fs workaround ===
  // process.cwd() is /var/task on Vercel and that filesystem is read-only.
  // Remotion's Chrome download path is derived from process.cwd() — it tries
  // mkdir('/var/task/.remotion/chrome-headless-shell') and fails with ENOENT.
  // Redirect cwd to /tmp (writable, ephemeral 512 MB) for the duration of the
  // render. `bundlePath` was already captured above as an ABSOLUTE path so
  // the cwd swap doesn't break bundle resolution. We restore the original cwd
  // in the finally block so subsequent requests on the same warm instance
  // aren't affected.
  const ORIGINAL_CWD = process.cwd();
  const REMOTION_TMP_CWD = "/tmp/remotion-cwd";
  await fs.mkdir(REMOTION_TMP_CWD, { recursive: true });
  process.chdir(REMOTION_TMP_CWD);

  try {
    const inputProps = {
      photos: renderInput.inputProps.photos,
      framesPerPhoto: renderInput.inputProps.framesPerPhoto,
    };

    console.error(
      `[render-reel] START compositionId=${COMPOSITION_ID} ` +
        `photos=${inputProps.photos.length} framesPerPhoto=${inputProps.framesPerPhoto} ` +
        `renderId=${renderId} cwd=${process.cwd()} bundlePath=${bundlePath}`,
    );

    // Resolve a Lambda-friendly Chromium binary. @sparticuz/chromium ships
    // the bundled shared libs (libnspr4, libnss3, fonts, etc.) that Vercel's
    // Node runtime lacks. Without this Remotion's default Chrome download
    // fails to launch with "libnspr4.so: cannot open shared object file".
    const browserExecutable = await chromium.executablePath();

    const composition = await selectComposition({
      serveUrl: bundlePath,
      id: COMPOSITION_ID,
      inputProps,
      browserExecutable,
    });

    const renderStart = Date.now();

    await renderMedia({
      composition,
      serveUrl: bundlePath,
      codec: "h264",
      outputLocation: tempFile,
      inputProps,
      imageFormat: "jpeg",
      pixelFormat: "yuv420p",
      crf: 23,
      muted: true,
      browserExecutable,
    });

    const renderMs = Date.now() - renderStart;
    console.error(`[render-reel] renderMedia done in ${renderMs}ms`);

    const fileBuffer = await fs.readFile(tempFile);
    const sizeBytes = fileBuffer.length;

    const admin = createStorageAdminClient();
    const { error: uploadError } = await admin.storage
      .from(BUCKET)
      .upload(storagePath, fileBuffer, {
        contentType: "video/mp4",
        upsert: false,
      });

    if (uploadError) {
      throw new Error(`Storage upload failed: ${uploadError.message}`);
    }

    const { data: signedData, error: signedError } = await admin.storage
      .from(BUCKET)
      .createSignedUrl(storagePath, SIGNED_URL_TTL_SEC);

    if (signedError || !signedData?.signedUrl) {
      throw new Error("Failed to create signed URL after upload.");
    }

    const durationSec = composition.durationInFrames / composition.fps;
    console.error(
      `[render-reel] DONE storagePath=${storagePath} ` +
        `sizeBytes=${sizeBytes} durationSec=${durationSec.toFixed(2)} renderMs=${renderMs}`,
    );

    return NextResponse.json({
      jobId: storagePath,
      assetUrl: signedData.signedUrl,
      durationSec,
      sizeBytes,
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.error(`[render-reel] ERROR renderId=${renderId}:`, message);
    return NextResponse.json({ error: message }, { status: 500 });
  } finally {
    try {
      process.chdir(ORIGINAL_CWD);
    } catch (cwdErr) {
      console.error(`[render-reel] failed to restore cwd: ${cwdErr instanceof Error ? cwdErr.message : cwdErr}`);
    }
    await fs.unlink(tempFile).catch(() => {});
  }
}
