/**
 * POST /api/admin/remotion/render-reel?reel={slug}
 *
 * Renders the configured photo reel as an h264 MP4. Reads composition config
 * from scratch/j2-{slug}-render-input.json (generated by scripts/upload-reel-photos.ts).
 *
 * Auth: cookie-bound Supabase session.
 * Flag: FEATURE_REMOTION=1 required.
 * Memory: 3 GB (Vercel Pro).
 */

import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { randomUUID } from "node:crypto";

import { NextResponse } from "next/server";
import chromium from "@sparticuz/chromium";
import { renderMedia, selectComposition } from "@remotion/renderer";
import { createClient as createSupabaseClient } from "@supabase/supabase-js";

import { isRemotionEnabled } from "@/lib/creatives/types";
import { createClient } from "@/lib/supabase/server";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const maxDuration = 600;
export const config = { memory: 3008 };

const BUCKET = "campaign-assets";
const COMPOSITION_ID = "PhotoReelStatic";
const SIGNED_URL_TTL_SEC = 60 * 60 * 24 * 7;

// Allowlist of valid reel slugs. Extend when adding new reels.
const ALLOWED_REELS = new Set(["bridge", "woods"]);
const DEFAULT_REEL = "bridge";

interface RenderInput {
  compositionId: string;
  inputProps: {
    photos: string[];
    framesPerPhoto: number;
    zoom?: boolean;
  };
}

function getBundlePath(): string {
  return path.join(process.cwd(), ".remotion/bundle");
}

function sanitizeReelSlug(value: string | null): string {
  if (!value) return DEFAULT_REEL;
  const clean = value.toLowerCase().replace(/[^a-z0-9-]/g, "");
  return ALLOWED_REELS.has(clean) ? clean : DEFAULT_REEL;
}

function createStorageAdminClient() {
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!supabaseUrl || !serviceRoleKey) {
    throw new Error(
      "Supabase storage admin requires NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY.",
    );
  }

  return createSupabaseClient(supabaseUrl, serviceRoleKey, {
    auth: { persistSession: false },
  });
}

async function readRenderInput(reel: string): Promise<RenderInput> {
  const filePath = path.join(process.cwd(), `scratch/j2-${reel}-render-input.json`);
  try {
    const raw = await fs.readFile(filePath, "utf-8");
    return JSON.parse(raw) as RenderInput;
  } catch {
    throw new Error(
      `scratch/j2-${reel}-render-input.json not found. ` +
        `Run \`REEL_TARGET=${reel} npx tsx scripts/upload-reel-photos.ts\` locally first and commit the output.`,
    );
  }
}

export async function POST(request: Request): Promise<NextResponse> {
  if (!isRemotionEnabled()) {
    return NextResponse.json(
      {
        error:
          "FEATURE_REMOTION is off — enable it in environment variables to run renders.",
      },
      { status: 503 },
    );
  }

  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: "Unauthorised" }, { status: 401 });
  }

  const { searchParams } = new URL(request.url);
  const reel = sanitizeReelSlug(searchParams.get("reel"));

  const bundlePath = getBundlePath();
  try {
    await fs.access(bundlePath);
  } catch {
    return NextResponse.json(
      {
        error:
          "Remotion bundle not found. Run `npm run bundle-remotion` before deploying.",
      },
      { status: 500 },
    );
  }

  let renderInput: RenderInput;
  try {
    renderInput = await readRenderInput(reel);
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return NextResponse.json({ error: message }, { status: 500 });
  }

  if (!Array.isArray(renderInput.inputProps?.photos) || renderInput.inputProps.photos.length === 0) {
    return NextResponse.json(
      { error: `Render input for reel "${reel}" has no photos. Re-run the upload script.` },
      { status: 500 },
    );
  }

  const renderId = randomUUID();
  const storagePath = `remotion-renders/${user.id}/${reel}-${renderId}.mp4`;
  const tempFile = path.join(os.tmpdir(), `remotion-reel-${reel}-${renderId}.mp4`);

  // chdir to /tmp because /var/task is read-only; Remotion writes Chrome cache
  // relative to process.cwd().
  const ORIGINAL_CWD = process.cwd();
  const REMOTION_TMP_CWD = "/tmp/remotion-cwd";
  await fs.mkdir(REMOTION_TMP_CWD, { recursive: true });
  process.chdir(REMOTION_TMP_CWD);

  try {
    const inputProps = {
      photos: renderInput.inputProps.photos,
      framesPerPhoto: renderInput.inputProps.framesPerPhoto,
      zoom: renderInput.inputProps.zoom ?? false,
    };

    console.error(
      `[render-reel] START reel=${reel} compositionId=${COMPOSITION_ID} ` +
        `photos=${inputProps.photos.length} framesPerPhoto=${inputProps.framesPerPhoto} ` +
        `renderId=${renderId} cwd=${process.cwd()} bundlePath=${bundlePath}`,
    );

    const browserExecutable = await chromium.executablePath();

    const composition = await selectComposition({
      serveUrl: bundlePath,
      id: COMPOSITION_ID,
      inputProps,
      browserExecutable,
    });

    const renderStart = Date.now();

    await renderMedia({
      composition,
      serveUrl: bundlePath,
      codec: "h264",
      outputLocation: tempFile,
      inputProps,
      imageFormat: "jpeg",
      pixelFormat: "yuv420p",
      crf: 23,
      muted: true,
      browserExecutable,
      // concurrency=1 required to fit 1080x1920 frame in 3 GB Lambda.
      concurrency: 1,
    });

    const renderMs = Date.now() - renderStart;
    console.error(`[render-reel] reel=${reel} renderMedia done in ${renderMs}ms`);

    const fileBuffer = await fs.readFile(tempFile);
    const sizeBytes = fileBuffer.length;

    const admin = createStorageAdminClient();
    const { error: uploadError } = await admin.storage
      .from(BUCKET)
      .upload(storagePath, fileBuffer, {
        contentType: "video/mp4",
        upsert: false,
      });

    if (uploadError) {
      throw new Error(`Storage upload failed: ${uploadError.message}`);
    }

    const { data: signedData, error: signedError } = await admin.storage
      .from(BUCKET)
      .createSignedUrl(storagePath, SIGNED_URL_TTL_SEC);

    if (signedError || !signedData?.signedUrl) {
      throw new Error("Failed to create signed URL after upload.");
    }

    const durationSec = composition.durationInFrames / composition.fps;
    console.error(
      `[render-reel] DONE reel=${reel} storagePath=${storagePath} ` +
        `sizeBytes=${sizeBytes} durationSec=${durationSec.toFixed(2)} renderMs=${renderMs}`,
    );

    return NextResponse.json({
      jobId: storagePath,
      reel,
      assetUrl: signedData.signedUrl,
      durationSec,
      sizeBytes,
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.error(`[render-reel] ERROR reel=${reel} renderId=${renderId}:`, message);
    return NextResponse.json({ error: message }, { status: 500 });
  } finally {
    try {
      process.chdir(ORIGINAL_CWD);
    } catch (cwdErr) {
      console.error(`[render-reel] failed to restore cwd: ${cwdErr instanceof Error ? cwdErr.message : cwdErr}`);
    }
    await fs.unlink(tempFile).catch(() => {});
  }
}
