/**
 * CAPTURED 2026-09-15 — `/adgroup/get/` accepted `fields` names,
 * complete (152), advertiser 7639802149165301776 (Ironworks).
 *
 * Source: the **error body**, not a success response. Re-triggered
 * against prod (still on `99be163`, still sending `connection_type`)
 * on campaign 1874233177915634. TikTok returns the set unordered —
 * order differs per call — so the array below is sorted.
 *
 * Header: captured from the live `/adgroup/get/` error body,
 * 2026-09-15, complete (152).
 *
 * WHAT THIS FILE PROVES, AND WHAT IT DOES NOT
 * - It proves which names TikTok *accepts* in `/adgroup/get/` `fields`.
 *   It says nothing about what a success body *returns*.
 * - It says nothing about `/ad/get/`. `display_name` and `ad_format`
 *   stay off `AD_GET_FIELDS` until that list is captured the same way.
 * - `REJECTED` is exhaustive for what we have driven: TikTok reports
 *   one offending index per request.
 */

/** Names TikTok's 2026-09-15 error body listed as acceptable. Complete (152). */
export const TIKTOK_ADGROUP_GET_ACCEPTED_FIELDS: readonly string[] = [
  "actions",
  "adgroup_app_profile_page_state",
  "adgroup_app_profile_page_type",
  "adgroup_id",
  "adgroup_name",
  "advertiser_id",
  "age_groups",
  "app_config",
  "app_download_url",
  "app_id",
  "app_type",
  "attribution_event_count",
  "audience_ids",
  "audience_rule",
  "audience_type",
  "auto_targeting_enabled",
  "automated_keywords_enabled",
  "bid_display_mode",
  "bid_price",
  "bid_type",
  "billing_event",
  "blocked_pangle_app_ids",
  "brand_safety_partner",
  "brand_safety_type",
  "budget",
  "budget_mode",
  "campaign_automation_type",
  "campaign_id",
  "campaign_name",
  "carrier_ids",
  "catalog_authorized_bc_id",
  "catalog_id",
  "category_exclusion_ids",
  "category_id",
  "click_attribution_window",
  "comment_disabled",
  "contextual_tag_ids",
  "conversion_bid_price",
  "conversion_id",
  "conversion_window",
  "cpm",
  "cpv_video_duration",
  "create_time",
  "creative_material_mode",
  "custom_conversion_id",
  "dayparting",
  "deep_bid_type",
  "deep_cpa_bid",
  "deep_funnel_event_source",
  "deep_funnel_event_source_id",
  "deep_funnel_optimization_event",
  "deep_funnel_optimization_status",
  "delivery_mode",
  "device_model_ids",
  "device_price_ranges",
  "discount_amount",
  "discount_percentage",
  "discount_type",
  "engaged_view_attribution_window",
  "excluded_audience_ids",
  "excluded_custom_actions",
  "excluded_pangle_audience_package_ids",
  "feed_type",
  "frequency",
  "frequency_schedule",
  "gender",
  "household_income",
  "identity_authorized_bc_id",
  "identity_id",
  "identity_type",
  "included_custom_actions",
  "included_pangle_audience_package_ids",
  "interest_category_ids",
  "interest_keyword_ids",
  "inventory_filter_enabled",
  "ios14_quota_type",
  "ios14_targeting",
  "is_hfss",
  "is_lhf_compliance",
  "is_new_structure",
  "is_smart_performance_campaign",
  "isp_ids",
  "keywords",
  "languages",
  "location_ids",
  "message_event_set_id",
  "messaging_app_account_id",
  "messaging_app_type",
  "min_android_version",
  "min_ios_version",
  "minis_id",
  "modify_time",
  "network_types",
  "next_day_retention",
  "operating_systems",
  "operation_status",
  "optimization_event",
  "optimization_goal",
  "package",
  "pacing",
  "phone_number",
  "phone_region_calling_code",
  "phone_region_code",
  "pixel_id",
  "placement_type",
  "placements",
  "pre_discount_budget",
  "pre_discount_cpm",
  "predict_impression",
  "product_set_id",
  "product_source",
  "promotion_target_type",
  "promotion_type",
  "promotion_website_type",
  "purchase_intention_keyword_ids",
  "purchased_impression",
  "purchased_reach",
  "rf_estimated_cpr",
  "rf_estimated_frequency",
  "rf_purchased_type",
  "roas_bid",
  "saved_audience_id",
  "schedule_end_time",
  "schedule_infos",
  "schedule_start_time",
  "schedule_type",
  "scheduled_budget",
  "search_keywords",
  "search_result_enabled",
  "secondary_optimization_event",
  "secondary_status",
  "share_disabled",
  "shopping_ads_retargeting_custom_audience_relation",
  "shopping_ads_retargeting_type",
  "shopping_ads_type",
  "skip_learning_phase",
  "smart_audience_enabled",
  "smart_interest_behavior_enabled",
  "spending_power",
  "split_test_group_id",
  "split_test_status",
  "statistic_type",
  "store_authorized_bc_id",
  "store_id",
  "targeting_expansion",
  "tiktok_subplacements",
  "topview_reach_range",
  "vbo_window",
  "vertical_sensitivity_id",
  "video_download_disabled",
  "view_attribution_window",
  "zipcode_ids",
];

/** Rejected live at `fields.32`. Not a TikTok field; it was guessed in #944. */
export const TIKTOK_ADGROUP_GET_REJECTED_FIELDS: readonly string[] = [
  "connection_type",
];
