export const ISO_COUNTRY_CODES: Record<string, string> = {
  NG: "Nigeria",
  GB: "United Kingdom",
  US: "United States",
  IE: "Ireland",
  FR: "France",
  DE: "Germany",
  IT: "Italy",
  ES: "Spain",
  CA: "Canada",
  AU: "Australia",
  NL: "Netherlands",
  BR: "Brazil",
  ZA: "South Africa",
  KE: "Kenya",
  AE: "United Arab Emirates",
  JP: "Japan",
  MX: "Mexico",
  AR: "Argentina",
  PT: "Portugal",
  BE: "Belgium",
  CH: "Switzerland",
  AT: "Austria",
  DK: "Denmark",
  SE: "Sweden",
  FI: "Finland",
  NO: "Norway",
  PL: "Poland",
  CZ: "Czech Republic",
  GR: "Greece",
  TR: "Turkey",
  IL: "Israel",
  SA: "Saudi Arabia",
  EG: "Egypt",
  MA: "Morocco",
  GH: "Ghana",
  TZ: "Tanzania",
  UG: "Uganda",
  IN: "India",
  PK: "Pakistan",
  ID: "Indonesia",
  MY: "Malaysia",
  SG: "Singapore",
  TH: "Thailand",
  PH: "Philippines",
  VN: "Vietnam",
  KR: "South Korea",
  TW: "Taiwan",
  HK: "Hong Kong",
  NZ: "New Zealand",
};
