-- ─────────────────────────────────────────────────────────────────────────────
-- Event key moments
-- A "moment" is a noteworthy date in an event's marketing calendar:
-- countdown phase ("3 months to go"), lineup drop, press hit, or any other
-- custom milestone Matas wants surfaced inline in the daily plan grid.
--
-- Two sources:
--   - source='auto' rows are time-based phase markers regenerated by the
--     application whenever an event is created or its event_date changes.
--     Lifecycle is owned by lib/db/event-key-moments.ts:regenerateAutoMoments
--     which deletes all auto rows for the event and re-inserts the canonical
--     set (currently 8 countdown markers from −90d to event day).
--   - source='manual' rows are user-curated (lineup drops, press, etc.)
--     and are NEVER touched by regenerate. The category check + the source
--     check are independent so a manual row can use any category.
--
-- budget_multiplier is a forward-compat hook for future pacing logic that
-- wants to lift spend on key dates (e.g. lineup drop = 1.5×). Null means
-- no multiplier; the pacing engine ignores it for now.
--
-- RLS scoped per user_id. Index on (event_id, moment_date) supports the
-- "load all moments for one event, key by date" lookup the plan grid does
-- on every render.
-- ─────────────────────────────────────────────────────────────────────────────

create table if not exists event_key_moments (
  id                 uuid        primary key default gen_random_uuid(),
  user_id            uuid        not null references auth.users (id) on delete cascade,
  event_id           uuid        not null references events (id)     on delete cascade,
  moment_date        date        not null,
  label              text        not null,
  category           text        not null,
  source             text        not null default 'manual',
  budget_multiplier  numeric(5, 2),
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),

  constraint event_key_moments_category_check check (
    category in ('phase', 'lineup', 'press', 'custom')
  ),
  constraint event_key_moments_source_check check (
    source in ('auto', 'manual')
  )
);

create index if not exists event_key_moments_event_date_idx
  on event_key_moments (event_id, moment_date);

alter table event_key_moments enable row level security;

drop policy if exists "Users can manage their own event_key_moments"
  on event_key_moments;
create policy "Users can manage their own event_key_moments"
  on event_key_moments
  for all
  using  (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- update_updated_at_column() defined in migration 003.
drop trigger if exists event_key_moments_updated_at on event_key_moments;
create trigger event_key_moments_updated_at
  before update on event_key_moments
  for each row execute procedure update_updated_at_column();
