import type { AdjustChannelRead, AdjustWindowReads } from "../../lib/plan/adjust-face.ts";

const FACTS = {
  meta: [
    { n: 6, noun: "audiences" },
    { n: 12, noun: "creatives" },
    { n: 4, noun: "ad sets" },
  ],
  tiktok: [{ n: 5, noun: "videos" }],
  google: [
    { n: 84, noun: "keywords" },
    { n: 31, noun: "negatives" },
  ],
};
import type { FrameId } from "./ids.ts";
import type { FrameFixture } from "./types.ts";
import {
  APR_20,
  AUG_4,
  AUG_11,
  DEC_4,
  EVENTS,
  MAR_18,
  SEP_1,
  WALK_NOW,
  draftedLaunches,
  emptyNames,
  idleLaunches,
  issues,
  j2TicketRows,
  leftAloneDecisions,
  listItem,
  liveLaunches,
  nxPurchaseRows,
  nxSignupRows,
  pausedLaunches,
  planOf,
  posterAsset,
  predictionRow,
  raiseDecision,
  refusalDecision,
  resolvedAll,
  resolvedMetaOnly,
} from "./builders.ts";

const SHEFFIELD = emptyNames({ "1073273492854557": "ELECTRIC STUDIOS SHEFFIELD" });

function dodReads(extra: Partial<AdjustWindowReads> = {}): AdjustWindowReads {
  return {
    spend: 558,
    metaRegs: 1086,
    metaPurchases: 16,
    tickets: null,
    reach: 42000,
    clicks: 2100,
    landingPageViews: 800,
    firstPartyLpv: null,
    dailyCostPerSignup: [0.48, 0.5, 0.51, 0.52, 0.51],
    channels: [
      { name: "Meta", spend: 558, results: 1086, connected: true },
      { name: "TikTok", spend: 0, results: 0, connected: false },
      { name: "Google", spend: 0, results: 0, connected: false },
    ],
    lastCreativeSnapshotAt: "2026-08-26T12:00:00.000Z",
    ...extra,
  };
}

function channels(...rows: AdjustChannelRead[]): AdjustChannelRead[] {
  return rows;
}

const dodLive = planOf({
  id: "plan-dod",
  status: "live",
  eventId: EVENTS.dod.id,
  unit: "click",
  value: 1.2,
  budget: { totalDaily: 35, metaDaily: 35, tiktokDaily: 0, googleDaily: 0 },
  startDate: "2026-08-27",
  endDate: "2026-08-27",
  startTime: "10:27",
  endTime: "11:13",
  launches: liveLaunches(),
});

const dodLaunch = planOf({
  id: "plan-dod-launch",
  eventId: EVENTS.dod.id,
  unit: "reg",
  value: 2.03,
  budget: { totalDaily: 35, metaDaily: 35, tiktokDaily: 0, googleDaily: 0 },
  startDate: "2026-08-27",
  endDate: "2026-12-03",
});

const schakDraft = planOf({
  id: "plan-schak",
  eventId: EVENTS.schak.id,
  unit: "reg",
  value: 1.6,
  startDate: "2026-09-20",
  endDate: "2026-12-17",
  launches: idleLaunches(),
});

const eedDraft = planOf({
  id: "plan-eed",
  eventId: EVENTS.eed.id,
  unit: "reg",
  value: 2.75,
  startDate: "2026-08-06",
  endDate: "2026-11-12",
  createdAt: "2026-08-06T09:00:00.000Z",
});

const mfDraft = planOf({
  id: "plan-mf",
  eventId: EVENTS.mf.id,
  unit: "reg",
  value: 1.32,
  startDate: "2026-07-10",
  endDate: "2026-10-15",
});

const folamourDraft = planOf({
  id: "plan-folamour",
  eventId: EVENTS.folamour.id,
  unit: "reg",
  value: 1.6,
  startDate: "2026-08-20",
  endDate: "2026-10-22",
});

const jamieDraft = planOf({
  id: "plan-jamie",
  eventId: EVENTS.jamie.id,
  unit: "reg",
  value: 1.6,
  startDate: "2026-08-20",
  endDate: "2026-09-06",
});

const brandDraft = planOf({
  id: "plan-brand",
  eventId: EVENTS.brand.id,
  unit: "view",
  value: 5.5,
  startDate: "2026-09-01",
  endDate: "2026-12-31",
});

const htBudget = { totalDaily: 100, metaDaily: 77, tiktokDaily: 23, googleDaily: 0 };

const htReady = planOf({
  id: "plan-ht",
  eventId: EVENTS.hardTechno.id,
  unit: "purchase",
  value: 12.89,
  budget: htBudget,
  startDate: "2026-07-10",
  endDate: "2026-08-01",
  launches: draftedLaunches(),
  createdAt: MAR_18,
});

const htLive = planOf({
  id: "plan-ht-live",
  status: "live",
  eventId: EVENTS.hardTechno.id,
  unit: "purchase",
  value: 12.89,
  budget: htBudget,
  startDate: "2026-03-18",
  endDate: "2026-08-01",
  launches: liveLaunches(MAR_18),
  createdAt: MAR_18,
});

const melodicLive = planOf({
  id: "plan-melodic",
  status: "live",
  eventId: EVENTS.melodic.id,
  unit: "purchase",
  budget: { totalDaily: 100, metaDaily: 77, tiktokDaily: 23, googleDaily: 0 },
  startDate: "2026-03-16",
  endDate: "2026-07-26",
  launches: liveLaunches("2026-03-16T09:00:00.000Z"),
});

const folamourLive = planOf({
  id: "plan-folamour-live",
  status: "live",
  eventId: EVENTS.folamour.id,
  unit: "reg",
  value: 1.6,
  startDate: "2026-08-20",
  endDate: "2026-10-22",
  launches: liveLaunches("2026-08-20T09:00:00.000Z"),
});

const mfLive = planOf({
  id: "plan-mf-live",
  status: "live",
  eventId: EVENTS.mf.id,
  unit: "reg",
  value: 2.75,
  startDate: "2026-07-29",
  endDate: "2026-10-15",
  launches: liveLaunches("2026-07-29T09:00:00.000Z"),
});

export const FRAME_FIXTURES: Record<FrameId, FrameFixture> = {
  L1: {
    kind: "list",
    id: "L1",
    title: "L1 · no plans",
    now: WALK_NOW,
    plans: [],
    events: [EVENTS.schak],
  },
  L2: {
    kind: "list",
    id: "L2",
    title: "L2 · Schak draft",
    now: WALK_NOW,
    tab: "drafts",
    plans: [listItem(schakDraft, EVENTS.schak, { drawerFix: { count: 2, channel: "Meta" } })],
    events: [EVENTS.schak],
  },
  L3: {
    kind: "list",
    id: "L3",
    title: "L3 · mixed, fold needs you",
    now: WALK_NOW,
    tab: "running",
    plans: [
      listItem(jamieDraft, EVENTS.jamie, { drawerFix: { count: 6, channel: null } }),
      listItem(folamourDraft, EVENTS.folamour),
      listItem(schakDraft, EVENTS.schak),
      listItem(dodLive, EVENTS.dod, { spent: 558 }),
    ],
    events: [EVENTS.jamie, EVENTS.folamour, EVENTS.schak, EVENTS.dod],
  },
  L4: {
    kind: "list",
    id: "L4",
    title: "L4 · D.O.D running, next is the show",
    now: WALK_NOW,
    tab: "running",
    plans: [listItem(dodLive, EVENTS.dod, { spent: 558 })],
    events: [EVENTS.dod],
  },
  L5: {
    kind: "list",
    id: "L5",
    title: "L5 · junk window",
    now: WALK_NOW,
    tab: "running",
    plans: [listItem(dodLive, EVENTS.dod, { spent: 66 })],
    events: [EVENTS.dod],
  },
  L6: {
    kind: "list",
    id: "L6",
    title: "L6 · nothing above the fold",
    now: WALK_NOW,
    tab: "running",
    plans: [listItem(dodLive, EVENTS.dod, { spent: 200 })],
    events: [EVENTS.dod],
  },
  A1: {
    kind: "launch",
    id: "A1",
    title: "A1 · Schak, n = 0",
    now: WALK_NOW,
    plan: schakDraft,
    event: EVENTS.schak,
    issues: issues(2, "meta"),
    resolved: resolvedMetaOnly(),
    identityNames: SHEFFIELD,
    assets: [posterAsset("schak-lineup.jpg")],
  },
  A2: {
    kind: "launch",
    id: "A2",
    title: "A2 · East End Dubs as at Tue 11 Aug, n = 1",
    now: AUG_11,
    plan: eedDraft,
    event: EVENTS.eed,
    benchmarkRows: nxSignupRows().filter((row) => row.event_id === "mf"),
    resolved: resolvedMetaOnly(),
    identityNames: SHEFFIELD,
    assets: [posterAsset("eed-lineup.jpg")],
  },
  A4: {
    kind: "launch",
    id: "A4",
    title: "A4 · D.O.D, n ≥ 3 at NX",
    now: "2026-08-20T12:00:00+01:00",
    plan: dodLaunch,
    event: EVENTS.dod,
    benchmarkRows: nxSignupRows(),
    resolved: resolvedMetaOnly(),
    identityNames: SHEFFIELD,
    assets: [posterAsset()],
    facts: FACTS,
  },
  A6: {
    kind: "launch",
    id: "A6",
    title: "A6 · Folamour as at Tue 1 Sep, presale not set",
    now: SEP_1,
    plan: folamourDraft,
    event: EVENTS.folamour,
    benchmarkRows: nxSignupRows(),
    resolved: resolvedMetaOnly(),
    identityNames: SHEFFIELD,
    assets: [posterAsset("folamour.jpg")],
  },
  A8: {
    kind: "launch",
    id: "A8",
    title: "A8 · D.O.D on sale, per purchase",
    now: WALK_NOW,
    plan: { ...dodLaunch, intent: { ...dodLaunch.intent, target: { value: 33.56, unit: "purchase" } } },
    event: EVENTS.dod,
    benchmarkRows: [...nxSignupRows(), ...nxPurchaseRows()],
    resolved: resolvedMetaOnly(),
    identityNames: SHEFFIELD,
    assets: [posterAsset()],
  },
  A9: {
    kind: "launch",
    id: "A9",
    title: "A9 · Brand Awareness (Always-On)",
    now: WALK_NOW,
    plan: brandDraft,
    event: EVENTS.brand,
    resolved: resolvedAll(),
    assets: [],
  },
  A10: {
    kind: "launch",
    id: "A10",
    title: "A10 · junk window",
    now: WALK_NOW,
    plan: dodLive,
    event: EVENTS.dod,
    resolved: resolvedMetaOnly(),
    identityNames: SHEFFIELD,
    liveSpend: 558,
  },
  A11: {
    kind: "launch",
    id: "A11",
    title: "A11 · TikTok not connected, share > 0",
    now: WALK_NOW,
    plan: planOf({
      id: "plan-a11",
      eventId: EVENTS.schak.id,
      budget: { totalDaily: 40, metaDaily: 28, tiktokDaily: 12, googleDaily: 0 },
    }),
    event: EVENTS.schak,
    issues: [
      {
        id: "tt-unconnected",
        adapter: "tiktok",
        field: "identity",
        message: "TikTok has 30% of the budget but no account — connect, or set TikTok to 0",
        blocking: true,
        href: "/tiktok",
      },
    ],
    resolved: resolvedMetaOnly(),
    identityNames: SHEFFIELD,
  },
  A13: {
    kind: "launch",
    id: "A13",
    title: "A13 · Hard Techno ready as at Wed 18 Mar",
    now: MAR_18,
    plan: htReady,
    event: EVENTS.hardTechno,
    benchmarkRows: j2TicketRows("purchase"),
    resolved: resolvedAll(),
    facts: FACTS,
    assets: [posterAsset("hard-techno.jpg")],
  },
  A14: {
    kind: "launch",
    id: "A14",
    title: "A14 · 6 things to fix before TikTok can run as at Wed 18 Mar",
    now: MAR_18,
    plan: htReady,
    event: EVENTS.hardTechno,
    issues: issues(6, "tiktok"),
    benchmarkRows: j2TicketRows("purchase"),
    resolved: resolvedAll(),
    assets: [posterAsset("hard-techno.jpg")],
  },
  A15: {
    kind: "launch",
    id: "A15",
    title: "A15 · Hard Techno launched, paused as at Wed 18 Mar",
    now: MAR_18,
    plan: { ...htLive, launches: pausedLaunches(MAR_18) },
    event: EVENTS.hardTechno,
    benchmarkRows: j2TicketRows("purchase"),
    resolved: resolvedAll(),
    assets: [posterAsset("hard-techno.jpg")],
  },
  J0: {
    kind: "loading",
    id: "J0",
    title: "J0 · loading",
    now: WALK_NOW,
    plan: dodLive,
    event: EVENTS.dod,
  },
  J1: {
    kind: "adjust",
    id: "J1",
    title: "J1 · day 0, no reads yet as at Wed 18 Mar",
    now: MAR_18,
    plan: htLive,
    event: EVENTS.hardTechno,
    spent: 0,
    planned: 0,
    metaSignups: null,
    metaPurchases: null,
    tickets: null,
    endSet: true,
    resolved: resolvedAll(),
    benchmarkRows: j2TicketRows("signup"),
    adjustReads: {
      spend: 0,
      metaRegs: null,
      metaPurchases: null,
      tickets: null,
      reach: null,
      clicks: null,
      landingPageViews: null,
      firstPartyLpv: null,
      dailyCostPerSignup: [],
      channels: [],
      lastCreativeSnapshotAt: null,
    },
  },
  J2: {
    kind: "adjust",
    id: "J2",
    title: "J2 · D.O.D running, end not set",
    now: WALK_NOW,
    plan: dodLive,
    event: EVENTS.dod,
    spent: 558,
    planned: 350,
    metaSignups: 1086,
    metaPurchases: null,
    tickets: null,
    endSet: false,
    trend: [0.48, 0.5, 0.51, 0.52, 0.51],
    benchmarkRows: nxSignupRows(),
    identityNames: SHEFFIELD,
    resolved: resolvedMetaOnly(),
    adjustReads: dodReads({ metaPurchases: null }),
    tagDomain: "dod-newcastle.com",
    assets: [posterAsset()],
  },
  J3: {
    kind: "adjust",
    id: "J3",
    title: "J3 · Hard Techno as at Mon 20 Apr, under pace, cost above your band",
    now: APR_20,
    plan: htLive,
    event: EVENTS.hardTechno,
    spent: 2588,
    planned: 3300,
    metaSignups: 553,
    metaPurchases: 84,
    tickets: 553,
    ticketSource: "unknown",
    benchmarkRows: j2TicketRows(),
    resolved: resolvedAll(),
    adjustReads: {
      spend: 2588,
      metaRegs: 553,
      metaPurchases: 84,
      tickets: 553,
      reach: 571098,
      clicks: 22319,
      landingPageViews: 6661,
      firstPartyLpv: null,
      dailyCostPerSignup: [],
      channels: channels(
        { name: "Meta", spend: 2588, results: 84, connected: true },
        { name: "TikTok", spend: 0, results: 0, connected: true },
        { name: "Google", spend: 0, results: 0, connected: true },
      ),
      lastCreativeSnapshotAt: null,
    },
  },
  J5: {
    kind: "adjust",
    id: "J5",
    title: "J5 · Folamour as at Tue 1 Sep — shape only",
    now: SEP_1,
    plan: folamourLive,
    event: EVENTS.folamour,
    spent: 0,
    planned: 0,
    metaSignups: null,
    metaPurchases: null,
    tickets: null,
    trend: null,
    decisions: [],
    resolved: resolvedMetaOnly(),
    identityNames: SHEFFIELD,
    adjustReads: {
      spend: 0,
      metaRegs: null,
      metaPurchases: null,
      tickets: null,
      reach: null,
      clicks: null,
      landingPageViews: null,
      firstPartyLpv: null,
      dailyCostPerSignup: [],
      channels: [],
      lastCreativeSnapshotAt: null,
    },
  },
  J7: {
    kind: "adjust",
    id: "J7",
    title: "J7 · Modern Funktion as at Tue 4 Aug, no usual yet",
    now: AUG_4,
    plan: mfLive,
    event: EVENTS.mf,
    spent: 1029,
    planned: 1029,
    metaSignups: 374,
    endSet: true,
    resolved: resolvedMetaOnly(),
    identityNames: SHEFFIELD,
    adjustReads: {
      spend: 1029,
      metaRegs: 374,
      metaPurchases: null,
      tickets: null,
      reach: null,
      clicks: null,
      landingPageViews: null,
      firstPartyLpv: null,
      dailyCostPerSignup: [],
      channels: channels({ name: "Meta", spend: 1029, results: 374, connected: true }),
      lastCreativeSnapshotAt: null,
    },
  },
  J8: {
    kind: "adjust",
    id: "J8",
    title: "J8 · Junction 2: Melodic as at Mon 20 Apr",
    now: APR_20,
    plan: melodicLive,
    event: EVENTS.melodic,
    spent: 3605,
    planned: 3600,
    metaSignups: 558,
    metaPurchases: 74,
    tickets: 558,
    ticketSource: "unknown",
    resolved: resolvedAll(),
    benchmarkRows: j2TicketRows(),
    adjustReads: {
      spend: 3605,
      metaRegs: 558,
      metaPurchases: 74,
      tickets: 558,
      reach: 1000935,
      clicks: 32519,
      landingPageViews: 11100,
      firstPartyLpv: null,
      dailyCostPerSignup: [],
      channels: channels({ name: "Meta", spend: 3605, results: 74, connected: true }),
      lastCreativeSnapshotAt: null,
    },
  },
  J9: {
    kind: "adjust",
    id: "J9",
    title: "J9 · our tag not measured",
    now: WALK_NOW,
    plan: dodLive,
    event: EVENTS.dod,
    spent: 558,
    planned: 350,
    metaSignups: 1086,
    endSet: false,
    tagDomain: "dod-newcastle.com",
    benchmarkRows: nxSignupRows(),
    identityNames: SHEFFIELD,
    resolved: resolvedMetaOnly(),
    adjustReads: dodReads({ firstPartyLpv: null }),
  },
  J12: {
    kind: "adjust",
    id: "J12",
    title: "J12 · Jamie Jones, TikTok earned nothing",
    now: WALK_NOW,
    plan: planOf({
      id: "plan-jamie-tt",
      status: "live",
      eventId: EVENTS.jamie.id,
      budget: { totalDaily: 40, metaDaily: 28, tiktokDaily: 12, googleDaily: 0 },
      launches: liveLaunches("2026-08-20T09:00:00.000Z"),
    }),
    event: EVENTS.jamie,
    spent: 1200,
    planned: 680,
    metaSignups: 80,
    resolved: resolvedAll(),
    adjustReads: {
      spend: 1200,
      metaRegs: 80,
      metaPurchases: null,
      tickets: null,
      reach: 10000,
      clicks: 200,
      landingPageViews: 40,
      firstPartyLpv: null,
      dailyCostPerSignup: [15, 14, 15],
      channels: channels(
        { name: "Meta", spend: 852, results: 80, connected: true },
        { name: "TikTok", spend: 348, results: 0, connected: true },
      ),
      lastCreativeSnapshotAt: null,
    },
  },
  J14: {
    kind: "adjust",
    id: "J14",
    title: "J14 · undo window open",
    now: WALK_NOW,
    plan: dodLive,
    event: EVENTS.dod,
    spent: 558,
    planned: 350,
    metaSignups: 1086,
    endSet: false,
    decisions: [raiseDecision()],
    benchmarkRows: nxSignupRows(),
    identityNames: SHEFFIELD,
    resolved: resolvedMetaOnly(),
    adjustReads: dodReads(),
  },
  J18: {
    kind: "adjust",
    id: "J18",
    title: "J18 · refusal row",
    now: WALK_NOW,
    plan: dodLive,
    event: EVENTS.dod,
    spent: 558,
    planned: 350,
    metaSignups: 1086,
    endSet: false,
    decisions: [refusalDecision(), ...leftAloneDecisions(36)],
    benchmarkRows: nxSignupRows(),
    identityNames: SHEFFIELD,
    resolved: resolvedMetaOnly(),
    adjustReads: dodReads(),
  },
  J19: {
    kind: "adjust",
    id: "J19",
    title: "J19 · creative reading locked",
    now: WALK_NOW,
    plan: dodLive,
    event: EVENTS.dod,
    spent: 558,
    planned: 350,
    metaSignups: 1086,
    endSet: false,
    lastCreativeSnapshotAt: "2026-08-26T12:00:00.000Z",
    benchmarkRows: nxSignupRows(),
    identityNames: SHEFFIELD,
    resolved: resolvedMetaOnly(),
    adjustReads: dodReads(),
  },
  J22: {
    kind: "adjust",
    id: "J22",
    title: "J22 · J2 as client",
    now: WALK_NOW,
    plan: dodLive,
    event: EVENTS.dod,
    role: "client",
    spent: 558,
    planned: 350,
    metaSignups: 1086,
    endSet: false,
    decisions: [raiseDecision()],
    benchmarkRows: nxSignupRows(),
    identityNames: SHEFFIELD,
    resolved: resolvedMetaOnly(),
    adjustReads: dodReads(),
  },
  E1: {
    kind: "learn",
    id: "E1",
    title: "E1 · D.O.D as at Fri 4 Dec · spend extrapolated at £56 per day",
    now: DEC_4,
    plan: { ...dodLive, status: "archived" },
    event: EVENTS.dod,
    prediction: predictionRow(),
    actual: 0.51,
    nextTime: 1.1,
    nextN: 6,
    nextBand: [0.62, 1.58],
    paceDaily: 35,
    pacePlanSaid: 3500,
    paceSpent: 5544,
    extrapolatedTitle: "E1 · D.O.D as at Fri 4 Dec · spend extrapolated at £56 per day",
    identityNames: SHEFFIELD,
  },
  E2: {
    kind: "learn",
    id: "E2",
    title: "E2 · no prediction was stored",
    now: DEC_4,
    plan: { ...dodLive, status: "archived" },
    event: EVENTS.dod,
    prediction: null,
    actual: 0.51,
    paceDaily: 35,
    pacePlanSaid: 3500,
    paceSpent: 5544,
    identityNames: SHEFFIELD,
  },
  E3: {
    kind: "learn",
    id: "E3",
    title: "E3 · locked until D.O.D closes",
    now: WALK_NOW,
    plan: dodLive,
    event: EVENTS.dod,
    locked: { days: 89, n: 1, of: 3 },
    paceDaily: 35,
    identityNames: SHEFFIELD,
  },
  E6: {
    kind: "learn",
    id: "E6",
    title: "E6 · E1 without next-time, role=client",
    now: DEC_4,
    plan: { ...dodLive, status: "archived" },
    event: EVENTS.dod,
    role: "client",
    prediction: predictionRow(),
    actual: 0.51,
    nextTime: 1.1,
    nextN: 6,
    paceDaily: 35,
    pacePlanSaid: 3500,
    paceSpent: 5544,
    identityNames: SHEFFIELD,
  },
};

export function getFrame(id: string): FrameFixture | undefined {
  return FRAME_FIXTURES[id as FrameId];
}
